### ISSUE TITLE
Start the stream from a specific point in time?

### ISSUE THREAD

**Issue by ShahramJ** [JamesKyburz/youtube-audio-stream#67] opened 2016-12-30 19:11 UTC
I'm trying to start the stream at a specific point in time of the duration of the audio. Is this possible? Any help would greatly be appreciated.

**Comment by JamesKyburz** [comment] 2017-01-28 10:19
Are you piping directly to the http response, like the example?

If so the problem is that the range responses aren't handled.

**Comment by JamesKyburz** [comment] 2017-01-28 10:20
Seems to be related to issue #51.

**Comment by JamesKyburz** [comment] 2017-03-11 17:07
Closing as there is currently no support for http ranges.

**Closed by JamesKyburz** 2017-03-11 17:07 UTC
